config/routes.rb
Rails.application.routes.draw do
  get 'pages/novas_tarefas'
  get 'pages/tarefas_feitas'
  get 'pages/home'
  resources :tarefas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tarefa
end

app/models/tarefa.rb
class Tarefa < ApplicationRecord
  enum prioridade: { baixa: 0, media: 1, alta: 2}
  enum atribuicao: [:icaro, :pedro, :dhiego, :yago]
  enum situacao: { nova: 0, feita: 1}
  enum porcetagem_terminado: [ '0%',  '10%',  '20%',  '30%',  '40%',  '50%',  '60%',  '70%',  '80%',  '90%',  '100%' ]

  # validades :
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern

  def current_user
    super || guest_user
  end

  def guest_user
    guest = GuestUser.new
    guest.name = "Guest User"
    guest.first_name = "Guest"
    guest.last_name = "User"
    guest.email = "guest@example.com"
    guest
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def novas_tarefas
    @tarefas = Tarefa.select { |a| a.situacao == 'nova'}
  end

  def tarefas_feitas
    @tarefas = Tarefa.select { |a| a.situacao == 'feita'}

    # Nota: Condição abaixo seleciona o method e mapeia o mesmo usando recude
    # object.select{|r| r.method?}.map(&:method)&.reduce(&:+)&.uniq || []
  end

  def home

  end
end

app/controllers/tarefas_controller.rb
class TarefasController < ApplicationController
  before_action :set_tarefa, only: [:show, :edit, :update, :destroy]

  # GET /tarefas
  # GET /tarefas.json
  def index
    @tarefas = Tarefa.all
  end

  # GET /tarefas/1
  # GET /tarefas/1.json
  def show
  end

  # GET /tarefas/new
  def new
    @tarefa = Tarefa.new
  end

  # GET /tarefas/1/edit
  def edit
  end

  # POST /tarefas
  # POST /tarefas.json
  def create
    @tarefa = Tarefa.new(tarefa_params)

    respond_to do |format|
      if @tarefa.save
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully created.' }
        format.json { render :show, status: :created, location: @tarefa }
      else
        format.html { render :new }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tarefas/1
  # PATCH/PUT /tarefas/1.json
  def update
    respond_to do |format|
      if @tarefa.update(tarefa_params)
        format.html { redirect_to @tarefa, notice: 'Tarefa was successfully updated.' }
        format.json { render :show, status: :ok, location: @tarefa }
      else
        format.html { render :edit }
        format.json { render json: @tarefa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarefas/1
  # DELETE /tarefas/1.json
  def destroy
    @tarefa.destroy
    respond_to do |format|
      format.html { redirect_to tarefas_url, notice: 'Tarefa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarefa
      @tarefa = Tarefa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tarefa_params
      params.require(:tarefa).permit(:titulo, :descricao, :situacao, :prioridade, :atribuicao, :inicio, :data_prevista, :tempo_estimado, :porcetagem_terminado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper style = ''
     if current_user.is_a?(GuestUser)
       (link_to 'register', new_user_registration_path, class: style) +
       " ".html_safe +
       (link_to 'login', new_user_session_path, class: style)
     else
       (link_to 'logout', destroy_user_session_path, method: :delete, class: style) +
       (link_to 'edit profile', edit_user_registration_path, class: style)
     end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tarefas_helper.rb
module TarefasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskWall</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Tarefas</h1>

<%= link_to 'Criar nova tarefa', new_tarefa_path, class: 'btn btn-primary'  %>
<%= link_to 'Novas tarefas',  pages_novas_tarefas_path, class: 'btn btn-primary'  %>
<%= link_to 'Tarefas Feitas', pages_tarefas_feitas_path, class: 'btn btn-primary'  %>

app/views/pages/novas_tarefas.html.erb
<h1>Novas Tarefas</h1>
<nav aria-label="Breadcrumb" class="breadcrumb">
  <%= link_to "Home", root_path, class: 'breadcrumb-item'%>
  <span class="breadcrumb-item active">Novas tarefas</span>
</nav>

  <table class="table table-hover">
      <thead>
        <tr class="text-left">
          <th><h5>Titulo</h5></th>
          <th><h5>Situação</h5></th>
          <th><h5>Prioridade</h5></th>
          <th><h5>Atribuição</h5></th>
          <th><h5>Data de inicio</h5></th>
          <th><h5>Data prevista</h5></th>
          <th><h5>Porcentagem concluida</h5></th>
          <th></th>
        </tr>
      </thead>

  <tbody id="table">
    <% @tarefas.each do |tarefa| %>
      <tr>
        <th><%= link_to tarefa.titulo, tarefa %> <small class="text-muted">Published <%= distance_of_time_in_words(tarefa.created_at, Time.now) %></small></th>
        <td><%= tarefa.situacao %></td>
        <td><%= tarefa.prioridade %></td>
        <td><%= tarefa.atribuicao %></td>
        <td><%= tarefa.inicio %></td>
        <td><%= tarefa.data_prevista %></td>
        <td><%= tarefa.porcetagem_terminado %></td>

        <th class="text-right">
          <%= link_to edit_tarefa_path(tarefa), class: 'btn btn-primary' do %>
          <%= fa_icon 'edit', style: "font-size:23px" %>
          <% end %>

          <%= link_to tarefa, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
          <%= fa_icon 'trash', style: "font-size:23px" %>
          <% end %>
        </th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/tarefas_feitas.html.erb
<h1>Tarefas Feitas</h1>
<nav aria-label="Breadcrumb" class="breadcrumb">
  <%= link_to "Home", root_path, class: 'breadcrumb-item'%>
  <span class="breadcrumb-item active">Tarefas Feitas</span>
</nav>
  <table class="table table-hover"">
      <thead>
        <tr class="text-left">
          <th><h5>Titulo</h5></th>
          <th><h5>Situação</h5></th>
          <th><h5>Prioridade</h5></th>
          <th><h5>Atribuição</h5></th>
          <th><h5>Data de inicio</h5></th>
          <th><h5>Data prevista</h5></th>
          <th><h5>Porcentagem concluida</h5></th>
          <th></th>
        </tr>
      </thead>

  <tbody id="table">
    <% @tarefas.each do |tarefa| %>
      <tr>
        <th><%= link_to tarefa.titulo, tarefa %> <small class="text-muted">Published <%= distance_of_time_in_words(tarefa.created_at, Time.now) %></small></th>
        <td><%= tarefa.situacao %></td>
        <td><%= tarefa.prioridade %></td>
        <td><%= tarefa.atribuicao %></td>
        <td><%= tarefa.inicio %></td>
        <td><%= tarefa.data_prevista %></td>
        <td><%= tarefa.porcetagem_terminado %></td>

        <th class="text-right">
          <%= link_to edit_tarefa_path(tarefa), class: 'btn btn-primary' do %>
          <%= fa_icon 'edit', style: "font-size:23px" %>
          <% end %>

          <%= link_to tarefa, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
          <%= fa_icon 'trash', style: "font-size:23px" %>
          <% end %>
        </th>
      </tr>


    <% end %>
  </tbody>
</table>

app/views/tarefas/_admin_actions.html.erb
<nav class="breadcrumb blogcrumb">
  <%= link_to fa_icon(blog_status(tarefa)), toggle_status_blog_path(tarefa), style: blog_status_color(tarefa) %>
  <%= link_to fa_icon('pencil-square-o'), edit_blog_path(tarefa)%>
  <%= link_to fa_icon('trash-o'), tarefa, method: :delete, data: { confirm: 'Você tem certeza?' }%>
</nav>

app/views/tarefas/_form.html.erb
<%= form_for(@tarefa) do |f| %>
  <% if @tarefa.errors.any? %>
    <% @tarefa.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>
<div class='row'>
  <div class="col-md-6">
    <div class="form-group">
      <div class="form-group">
        <%= f.label :titulo %>
        <%= f.text_field :titulo, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :descricao %>
        <%= f.text_area :descricao, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.collection_select :situacao,
            Tarefa.situacoes.keys.map{|s| [s, s.capitalize]},
              :first, :last, {include_blank: 'situacao'},
              {class: 'form-control'} %>
      </div>


      <div class="form-group">
        <%= f.collection_select :prioridade,
            Tarefa.prioridades.keys.map{|s| [s, s.capitalize]},
              :first, :last, {include_blank: 'prioridade'},
              {class: 'form-control'} %>
      </div>

      <div class="form-group">
        <%= f.collection_select :atribuicao,
            Tarefa.atribuicoes.keys.map{|s| [s, s.capitalize]},
              :first, :last, {include_blank: 'atribuições'},
              {class: 'form-control'} %>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="form-group">

      <div class="form-group">
        <%= f.label :inicio %>
        <%= f.text_field :inicio, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :data_prevista %>
        <%= f.text_field :data_prevista, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :tempo_estimado %>
        <%= f.text_field :tempo_estimado, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.collection_select :porcetagem_terminado,
            Tarefa.porcetagens_terminados.keys.map{|s| [s, s.capitalize]},
              :first, :last, {include_blank: 'porcentagem terminada'},
              {class: 'form-control'} %>
      </div>

    </div>
  </div>
</div>

<div class="actions">
  <%= f.submit 'Criar tarefa', class: 'btn btn-primary' %>
</div>
&nbsp;
<% end %>

app/views/tarefas/edit.html.erb
<div class="col-sm-8 blog-main">

  <h1>Editando Tarefa</h1>

  <%= render 'form', tarefa: @tarefa %>

  <%= link_to 'Ver tarefa', @tarefa, class: 'btn btn-primary' %> |
  <%= link_to 'Voltar', tarefa_path, class: 'btn btn-primary' %>

</div>

app/views/tarefas/index.html.erb
<h1> Tarefas</h1>
<nav aria-label="Breadcrumb" class="breadcrumb">
  <%= link_to "Home", root_path, class: 'breadcrumb-item'%>
  <span class="breadcrumb-item active">Novas tarefas</span>
</nav>

  <table class="table table-hover">
      <thead>
        <tr class="text-left">
          <th><h5>Titulo</h5></th>
          <th><h5>Situação</h5></th>
          <th><h5>Prioridade</h5></th>
          <th><h5>Atribuição</h5></th>
          <th><h5>Data de inicio</h5></th>
          <th><h5>Data prevista</h5></th>
          <th><h5>Porcentagem concluida</h5></th>
          <th></th>
        </tr>
      </thead>

  <tbody id="table">
    <% @tarefas.each do |tarefa| %>
      <tr>
        <th><%= link_to tarefa.titulo, tarefa %> <small class="text-muted">Published <%= distance_of_time_in_words(tarefa.created_at, Time.now) %></small></th>
        <td><%= tarefa.situacao %></td>
        <td><%= tarefa.prioridade %></td>
        <td><%= tarefa.atribuicao %></td>
        <td><%= tarefa.inicio %></td>
        <td><%= tarefa.data_prevista %></td>
        <td><%= tarefa.porcetagem_terminado %></td>

        <th class="text-right">
          <%= link_to edit_tarefa_path(tarefa), class: 'btn btn-primary' do %>
          <%= fa_icon 'edit', style: "font-size:23px" %>
          <% end %>

          <%= link_to tarefa, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
          <%= fa_icon 'trash', style: "font-size:23px" %>
          <% end %>
        </th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tarefas/new.html.erb
<div class="col-sm-8">

  <h1>Nova Tarefa</h1>

  <%= render 'form', tarefa: @tarefa %>
  <%= link_to 'Voltar', root_path, class: 'btn btn-primary' %>

</div>

app/views/tarefas/show.html.erb
<div class="col-sm-8 blog-main">

  <h2><%= @tarefa.titulo %></h2>

  <p>
    <strong>Descrição:</strong>
    <%= @tarefa.descricao %>
  </p>


  <p>
    <strong>Tempo estimado:</strong>
    <%= @tarefa.tempo_estimado %>
  </p>

</div>
<%= link_to 'Editar tarefa', edit_tarefa_path(@tarefa), class: 'btn btn-primary' %>

<%= link_to 'Ver novas tarefas', pages_novas_tarefas_path, class: 'btn btn-primary' %>
<%= link_to 'Ver tarefas feitas', pages_tarefas_feitas_path, class: 'btn btn-primary' %>